#!/usr/bin/env python3
"""Install NeuroClaw as an external-agent skill pack.

This installer creates a small "router skill" plus generated references. The
router skill gives the host agent a NeuroClaw persona and points it to the
local NeuroClaw repository for concrete neuroimaging, NeuroOracle, NeuroBench,
and model execution workflows.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).parent.parent.resolve()
SKILLS_ROOT = REPO_ROOT / "skills"
NEUROBENCH_ROOT = REPO_ROOT / "neurobench"
NEUROORACLE_ROOT = REPO_ROOT / "neurooracle"
MODELS_ROOT = REPO_ROOT / "models"
TASK_ATLAS = NEUROBENCH_ROOT / "task_atlas.json"

GENERATED_MARKER = "<!-- Generated by NeuroClaw installer/install_agent_integration.py -->"


@dataclass(frozen=True)
class InstallTarget:
    name: str
    root: Path


AGENT_TARGETS = [
    "codex",
    "claude-code",
    "cursor",
    "openclaw",
    "hermes",
    "workbuddy",
    "qclaw",
]


def _repo_path(path: Path) -> str:
    try:
        return str(path.resolve())
    except Exception:
        return str(path)


def _read_text(path: Path, max_chars: int | None = None) -> str:
    try:
        text = path.read_text(encoding="utf-8")
    except Exception:
        return ""
    if max_chars is not None and len(text) > max_chars:
        return text[:max_chars].rstrip() + "\n..."
    return text


def _strip_frontmatter(text: str) -> tuple[dict[str, str], str]:
    match = re.match(r"^---\s*\n(.*?)\n---\s*\n?", text, flags=re.DOTALL)
    if not match:
        return {}, text
    meta: dict[str, str] = {}
    for raw_line in match.group(1).splitlines():
        line = raw_line.strip()
        if not line or ":" not in line:
            continue
        key, value = line.split(":", 1)
        meta[key.strip()] = value.strip().strip("\"'")
    return meta, text[match.end() :]


def _first_heading_or_sentence(body: str) -> str:
    for line in body.splitlines():
        clean = line.strip(" #\t")
        if clean and not clean.startswith("```"):
            return clean[:180]
    compact = re.sub(r"\s+", " ", body).strip()
    return compact[:180]


def _discover_skills() -> list[dict[str, str]]:
    items: list[dict[str, str]] = []
    if not SKILLS_ROOT.exists():
        return items
    for skill_md in sorted(SKILLS_ROOT.glob("*/SKILL.md")):
        raw = _read_text(skill_md, max_chars=12000)
        meta, body = _strip_frontmatter(raw)
        name = meta.get("name") or skill_md.parent.name
        desc = meta.get("description") or _first_heading_or_sentence(body)
        items.append(
            {
                "name": name,
                "description": desc,
                "path": _repo_path(skill_md),
                "folder": skill_md.parent.name,
            }
        )
    return items


def _write_skill_catalog(ref_dir: Path) -> None:
    skills = _discover_skills()
    lines = [
        GENERATED_MARKER,
        "# NeuroClaw Skill Catalog",
        "",
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}",
        f"Repository: `{_repo_path(REPO_ROOT)}`",
        f"Skill root: `{_repo_path(SKILLS_ROOT)}`",
        "",
        "Use this catalog first. Read the full SKILL.md only for the selected workflow.",
        "",
        "| Skill | Description | Source |",
        "|---|---|---|",
    ]
    for item in skills:
        desc = item["description"].replace("|", "\\|")
        lines.append(f"| `{item['name']}` | {desc} | `{item['path']}` |")
    if not skills:
        lines.append("| - | No skills discovered. | - |")
    _write_generated(ref_dir / "skill_catalog.md", "\n".join(lines) + "\n")


def _write_neurobench_catalog(ref_dir: Path) -> None:
    lines = [
        GENERATED_MARKER,
        "# NeuroBench Catalog",
        "",
        f"Repository: `{_repo_path(REPO_ROOT)}`",
        f"NeuroBench root: `{_repo_path(NEUROBENCH_ROOT)}`",
        "",
        "NeuroBench evaluates whether an agent can execute neuroimaging workflows,",
        "model training, and cross-model evaluation tasks.",
        "",
        "Common commands:",
        "",
        "```bash",
        "python core/agent/main.py --benchmark",
        "python core/agent/main.py --benchmark --benchmark-compare-skills",
        "python core/agent/main.py --score-benchmark",
        "```",
        "",
    ]
    try:
        atlas = json.loads(TASK_ATLAS.read_text(encoding="utf-8"))
    except Exception:
        atlas = {}
    categories = (
        atlas.get("operational_layer", {})
        .get("categories", {})
        if isinstance(atlas, dict)
        else {}
    )
    if isinstance(categories, dict) and categories:
        lines.extend(["## Categories", ""])
        for key, data in categories.items():
            if not isinstance(data, dict):
                continue
            label = data.get("label", key)
            summary = data.get("summary", "")
            tasks = data.get("tasks", [])
            lines.append(f"### {label} (`{key}`)")
            if summary:
                lines.append(str(summary))
            if isinstance(tasks, list):
                preview = ", ".join(f"`{t}`" for t in tasks[:12])
                suffix = " ..." if len(tasks) > 12 else ""
                lines.append(f"Tasks: {preview}{suffix}")
            lines.append("")
    _write_generated(ref_dir / "neurobench_catalog.md", "\n".join(lines) + "\n")


def _write_autoresearch_reference(ref_dir: Path) -> None:
    text = f"""{GENERATED_MARKER}
# NeuroClaw AutoResearch Reference

Repository: `{_repo_path(REPO_ROOT)}`
NeuroOracle root: `{_repo_path(NEUROORACLE_ROOT)}`

Use this reference when the user asks for NeuroOracle, knowledge graph search,
hypothesis generation, novelty checking, critic review, plausibility scoring, or
case-study autoresearch.

## Recommended Workflow

Prefer the case-study-driven autoresearch route when a graph already exists:

```bash
bash neurooracle/run_case_study.sh cs2_transdiagnostic
bash neurooracle/run_case_study.sh cs3_pathway_mediation
```

Or call the CLI directly:

```bash
python -m neurooracle.src.hypothesis_cli --graph <graph.json> case-study <case_id> --output-dir <runs/case_id>
```

## Graph Build And Claim Extraction

Use these only when the user needs to rebuild or refresh the knowledge graph:

```bash
python -m neurooracle.phase1
python -m neurooracle.phase2 --broad --max-workers 12
python -m neurooracle.phase2 --diseases "Alzheimer's disease" --year-start 2025 --year-end 2025
```

## Agent Behavior

- Treat the graph as the source of structured neuroscience evidence.
- Prefer registered case studies over open-ended free generation.
- Preserve outputs, logs, graph paths, hypotheses, critic feedback, novelty, and
  plausibility scores in a run directory.
- Before launching long jobs, inspect the selected script and explain expected
  inputs, outputs, and runtime assumptions.
- Do not fabricate PubMed evidence or KG edges. If inputs are missing, say what
  graph, abstracts, or case-study files are required.
"""
    _write_generated(ref_dir / "autoresearch.md", text)


def _write_model_workflows(ref_dir: Path) -> None:
    model_dirs = [
        p.name
        for p in sorted(MODELS_ROOT.iterdir())
        if p.is_dir() and not p.name.startswith("__")
    ] if MODELS_ROOT.exists() else []
    lines = [
        GENERATED_MARKER,
        "# NeuroClaw Model Workflow Reference",
        "",
        f"Models root: `{_repo_path(MODELS_ROOT)}`",
        "",
        "Use this reference for brain model training, evaluation, sweeps, and",
        "NeuroBench model-training tasks.",
        "",
        "Common entry points:",
        "",
        "```bash",
        "python models/train_unified.py --help",
        "python models/scripts/run_benchmark.py --help",
        "```",
        "",
        "Discovered model folders:",
        "",
    ]
    if model_dirs:
        lines.extend(f"- `{name}`" for name in model_dirs)
    else:
        lines.append("- No model folders discovered.")
    _write_generated(ref_dir / "model_workflows.md", "\n".join(lines) + "\n")


def _router_skill_text() -> str:
    return f"""---
name: neuroclaw
description: Use NeuroClaw for neuroimaging, BIDS, fMRI, DWI, sMRI, FreeSurfer, FSL, NeuroOracle, NeuroBench, brain model training, and autoresearch.
---

# NeuroClaw Mode

You are operating in NeuroClaw mode inside the host agent.

NeuroClaw is a neuroscience-first research agent for executable neuroimaging
workflows, reproducible model execution, NeuroOracle autoresearch, and
NeuroBench evaluation. Use the local NeuroClaw repository as the source of
domain capability:

`{_repo_path(REPO_ROOT)}`

## Identity

When this skill is active, behave as NeuroClaw:

- Focus on neuroimaging, BIDS, fMRI, DWI, sMRI, EEG/MEG, PET, FreeSurfer, FSL,
  fMRIPrep, QSIPrep, Nilearn, MNE, NeuroOracle, NeuroBench, and brain model
  execution.
- Prefer executable workflows and reproducible commands over abstract advice.
- Inspect generated catalogs before reading full source files.
- Use NeuroClaw skills and scripts as implementation references.
- Keep scientific claims grounded in data, graph evidence, or cited literature.

## Reference Order

1. Read `references/skill_catalog.md` to choose a workflow skill.
2. Read `references/autoresearch.md` for NeuroOracle and autoresearch.
3. Read `references/neurobench_catalog.md` for benchmark tasks.
4. Read `references/model_workflows.md` for model training/evaluation.
5. Read the selected full `SKILL.md` or script from the NeuroClaw repository.

## Common Commands

```bash
python core/agent/main.py --web
python core/agent/main.py --benchmark
python core/agent/main.py --score-benchmark
bash neurooracle/run_case_study.sh cs2_transdiagnostic
python -m neurooracle.phase1
python -m neurooracle.phase2 --broad --max-workers 12
```

## Guardrails

- Do not read every NeuroClaw skill at once. Use the catalog and then inspect the
  narrow skill needed for the user task.
- Do not claim a pipeline has run unless commands were actually executed and
  outputs were checked.
- For long jobs, state expected inputs, outputs, and runtime assumptions first.
- If external datasets, licensed tools, API keys, or large compute are missing,
  say exactly what is missing and provide the closest reproducible dry-run path.
"""


def _write_generated(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _install_root(target: str, scope: str) -> Path:
    if target == "codex":
        base = Path.home() / ".codex" if scope == "user" else REPO_ROOT / ".codex"
    elif target == "claude-code":
        base = Path.home() / ".claude" if scope == "user" else REPO_ROOT / ".claude"
    elif target == "cursor":
        base = Path.home() / ".cursor" if scope == "user" else REPO_ROOT / ".cursor"
        return base / "rules"
    elif target == "openclaw":
        base = Path.home() / ".openclaw" if scope == "user" else REPO_ROOT / ".openclaw"
    elif target == "hermes":
        base = Path.home() / ".hermes" if scope == "user" else REPO_ROOT / ".hermes"
    elif target == "workbuddy":
        base = Path.home() / ".workbuddy" if scope == "user" else REPO_ROOT / ".workbuddy"
    elif target == "qclaw":
        base = Path.home() / ".qclaw" if scope == "user" else REPO_ROOT / ".qclaw"
    else:
        raise ValueError(f"Unknown target: {target}")
    return base / "skills" / "neuroclaw"


def _cursor_rule_text(ref_dir: Path) -> str:
    return f"""---
description: NeuroClaw mode for neuroimaging, NeuroOracle, NeuroBench, model workflows, and autoresearch.
globs:
  - "**/*"
alwaysApply: false
---

# NeuroClaw Mode

Use NeuroClaw mode when the task involves neuroimaging, BIDS, fMRI, DWI, sMRI,
FreeSurfer, FSL, fMRIPrep, QSIPrep, Nilearn, MNE, NeuroOracle, NeuroBench,
brain model training, or autoresearch.

NeuroClaw repository:

`{_repo_path(REPO_ROOT)}`

Before reading the full repository, inspect the generated references:

- `{_repo_path(ref_dir / "skill_catalog.md")}`
- `{_repo_path(ref_dir / "autoresearch.md")}`
- `{_repo_path(ref_dir / "neurobench_catalog.md")}`
- `{_repo_path(ref_dir / "model_workflows.md")}`

Behave as NeuroClaw: prioritize executable, reproducible neuroimaging workflows;
use NeuroClaw skills and scripts as implementation references; keep scientific
claims grounded in data, graph evidence, or cited literature; and do not claim a
pipeline has run unless commands were executed and outputs were checked.
"""


def _install_skill(target: str, scope: str) -> Path:
    root = _install_root(target, scope)
    if target == "cursor":
        ref_dir = root / "neuroclaw-references"
        root.mkdir(parents=True, exist_ok=True)
        _write_generated(root / "neuroclaw.mdc", _cursor_rule_text(ref_dir))
        _write_skill_catalog(ref_dir)
        _write_neurobench_catalog(ref_dir)
        _write_autoresearch_reference(ref_dir)
        _write_model_workflows(ref_dir)
        return root

    ref_dir = root / "references"
    root.mkdir(parents=True, exist_ok=True)
    _write_generated(root / "SKILL.md", _router_skill_text())
    _write_skill_catalog(ref_dir)
    _write_neurobench_catalog(ref_dir)
    _write_autoresearch_reference(ref_dir)
    _write_model_workflows(ref_dir)
    return root


def _append_persona_default(target: str, scope: str) -> Path | None:
    if scope != "user":
        return None
    if target == "claude-code":
        memory_path = Path.home() / ".claude" / "CLAUDE.md"
    elif target == "codex":
        memory_path = Path.home() / ".codex" / "NEUROCLAW.md"
    else:
        return None
    memory_path.parent.mkdir(parents=True, exist_ok=True)
    block = (
        "\n"
        f"{GENERATED_MARKER}\n"
        "For neuroscience, neuroimaging, BIDS, NeuroOracle, NeuroBench, brain model "
        "training, and autoresearch tasks, use the installed NeuroClaw skill and "
        "operate in NeuroClaw mode.\n"
    )
    existing = _read_text(memory_path)
    if "operate in NeuroClaw mode" not in existing:
        with memory_path.open("a", encoding="utf-8") as f:
            f.write(block)
    return memory_path


def _copy_to_output(path: Path, output: Path) -> None:
    if output.exists():
        shutil.rmtree(output)
    shutil.copytree(path, output)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Install NeuroClaw as an external-agent skill pack.",
    )
    parser.add_argument(
        "--target",
        choices=[*AGENT_TARGETS, "both", "all"],
        default="both",
        help="Host agent to install into.",
    )
    parser.add_argument(
        "--scope",
        choices=["user", "project"],
        default="user",
        help="Install into user home or this repository.",
    )
    parser.add_argument(
        "--persona-default",
        action="store_true",
        help="Add a small persistent NeuroClaw-mode hint where the host supports it.",
    )
    parser.add_argument(
        "--export",
        type=Path,
        default=None,
        help="Copy the generated skill pack to this directory after installation.",
    )
    args = parser.parse_args()

    if args.target == "both":
        targets = ["codex", "claude-code"]
    elif args.target == "all":
        targets = list(AGENT_TARGETS)
    else:
        targets = [args.target]
    installed: list[tuple[str, Path]] = []
    for target in targets:
        path = _install_skill(target, args.scope)
        installed.append((target, path))
        print(f"Installed NeuroClaw skill for {target}: {path}")
        if args.persona_default:
            memory_path = _append_persona_default(target, args.scope)
            if memory_path is not None:
                print(f"Updated persona hint for {target}: {memory_path}")

    if args.export is not None:
        export_root = args.export.resolve()
        export_root.mkdir(parents=True, exist_ok=True)
        for target, path in installed:
            _copy_to_output(path, export_root / target / "neuroclaw")
        print(f"Exported generated skill packs to: {export_root}")


if __name__ == "__main__":
    main()
